apiVersion: 1
contactPoints:
    - orgId: 1
      name: local-webhook-receiver
      receivers:
        - uid: afotuf9mkqz28b
          type: webhook
          settings:
            httpMethod: POST
            url: http://webhook-receiver:5000/webhook
          disableResolveMessage: false
